### PR TITLE
Updated SDE Sex to use direct reference codes rather than inline code…

### PR DESCRIPTION
**Pull request by brynrhodes**
… selectors

### CODE REVIEW

**Review by juliet-rubini — APPROVED** [review]
Reviewed and approved (with guidance from Bryn who opened the change)

**Review by JSRankins — COMMENTED** [review]
It appears that an incorrect Canonical is being provided for the v3-AdministrativeGender code system. Per [THO](https://terminology.hl7.org/CodeSystem-v3-AdministrativeGender.html), the Canonical is http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender.

**Comment by JSRankins** [comment]
Actually, the more I look into this, it becomes more complex. 
QI-Core STU 4.1.1 [Patient.gender](https://hl7.org/fhir/us/qicore/STU4.1.1/StructureDefinition-qicore-patient-definitions.html#Patient.gender) in STU 4 is bound to a value set, which uses the following code system: [http://hl7.org/fhir/administrative-gender](http://hl7.org/fhir/administrative-gender).
That is a FHIR code system as opposed to the v3-AdministrativeGender code system which is being implied by the URL in the revised SDE library: [http://hl7.org/fhir/v3/AdministrativeGender](http://hl7.org/fhir/v3/AdministrativeGender)
The binding is `required` for [Patient.gender](https://hl7.org/fhir/us/qicore/STU4.1.1/StructureDefinition-qicore-patient-definitions.html#Patient.gender) in STU 4, so even if we want to use the v3-AdministrativeGender code system, it doesn't appear that we can.
MADiE currently does not recognize http://hl7.org/fhir/administrative-gender code system, so a MADiE HD ticket will need to be submitted.
Thoughts?

**Comment by JSRankins** [comment]
Received word from MADiE team today (and confirmed) that MADiE now recognizes http://hl7.org/fhir/administrative-gender code system. SupplementalDataElements v3.5000 is now available in MADiE.

**Pull request merged**
